"""Remove unique constraints of user from index resource

Revision ID: 23722ef2d9a7
Revises: 834808374f57
Create Date: 2024-06-22 12:22:06.682886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23722ef2d9a7'
down_revision: Union[str, None] = '834808374f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_indexed_resource_user_id', table_name='indexed_resource')
    op.create_index(op.f('ix_indexed_resource_user_id'), 'indexed_resource', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexed_resource_user_id'), table_name='indexed_resource')
    op.create_index('ix_indexed_resource_user_id', 'indexed_resource', ['user_id'], unique=True)
    # ### end Alembic commands ###
