"""Make user id of dropbox token unique.

Revision ID: 6077cdae1296
Revises: 42bf99b9c791
Create Date: 2024-06-21 19:38:16.058986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6077cdae1296'
down_revision: Union[str, None] = '42bf99b9c791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dropbox_tokens_user_id', table_name='dropbox_tokens')
    op.create_index(op.f('ix_dropbox_tokens_user_id'), 'dropbox_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dropbox_tokens_user_id'), table_name='dropbox_tokens')
    op.create_index('ix_dropbox_tokens_user_id', 'dropbox_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
