"""Add expires in

Revision ID: ce0b3f125573
Revises: de9cbee3e64e
Create Date: 2024-06-21 21:50:37.292056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce0b3f125573'
down_revision: Union[str, None] = 'de9cbee3e64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropbox_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('dropbox_tokens', 'expires_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropbox_tokens', sa.Column('expires_in', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('dropbox_tokens', 'expires_at')
    # ### end Alembic commands ###
