"""Add expires in

Revision ID: de9cbee3e64e
Revises: 6077cdae1296
Create Date: 2024-06-21 21:31:44.950288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9cbee3e64e'
down_revision: Union[str, None] = '6077cdae1296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropbox_tokens', sa.Column('expires_in', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dropbox_tokens', 'expires_in')
    # ### end Alembic commands ###
