---
name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
